### ISSUE TITLE
Error generating colmap for single camera

### ISSUE THREAD

**Issue by shirgur** [graphdeco-inria/hierarchical-3d-gaussians#3]
Hi,

I have my own dataset with the same structure, but only a single directory "cam1" with images.

When I run the ```preprocess/generate_colmap.py``` it crashes with:
```shell
making custom matches...
Traceback (most recent call last):
  File "~/hierarchical-3d-gaussians/preprocess/make_colmap_custom_matcher.py", line 115, in <module>
    add_match(cam_id, matched_cam_id, current_image_file, matched_frame_id)
  File "~/hierarchical-3d-gaussians/preprocess/make_colmap_custom_matcher.py", line 102, in add_match
    matches_str.append(f"{cam_folder_list[cam_id]}/{current_image_file} {cam_folder_list[cam_id + matched_cam_id]}/{matched_image_file}\n")
                          ~~~~~~~~~~~~~~~^^^^^^^^
```

If I remove the "if" statement on line 88 [here](https://github.com/graphdeco-inria/hierarchical-3d-gaussians/blob/3bcfcf5d2b82b6843ba51455805de6a3617216d3/preprocess/make_colmap_custom_matcher.py#L88) it manages to pass, but I'm not sure it works...

Is this a bug? do you support single camera as well?

Thank you!

**Comment by ameuleman** [comment]
Hi, I'm not sure why this statement is there. How does the `camera_calibration/unrectified/matching.txt` look like?

**Comment by shirgur** [comment]
It looks reasonable I guess
```txt
...
cam1/frame_0003.jpg cam1/frame_0066.jpg
cam1/frame_0003.jpg cam1/frame_0130.jpg
cam1/frame_0004.jpg cam1/frame_0005.jpg
cam1/frame_0004.jpg cam1/frame_0007.jpg
cam1/frame_0004.jpg cam1/frame_0011.jpg
cam1/frame_0004.jpg cam1/frame_0019.jpg
cam1/frame_0004.jpg cam1/frame_0035.jpg
cam1/frame_0004.jpg cam1/frame_0067.jpg
cam1/frame_0004.jpg cam1/frame_0131.jpg
cam1/frame_0005.jpg cam1/frame_0006.jpg
cam1/frame_0005.jpg cam1/frame_0008.jpg
cam1/frame_0005.jpg cam1/frame_0012.jpg
...
```

**Comment by ameuleman** [comment]
Yes, it looks fine. Do you only have a few hundred images? If so, COLMAP's exhaustive matcher might be appropriate

**Comment by shirgur** [comment]
OK cool, thank you for the tip

Looks like removing the "if" statement is fine

**Comment by shankar-anantak** [comment]
Also experiencing the same issue...

When i comment out the if statement, it crashes here:

```
E0726 22:25:12.706657 15466 pairing.cc:74] Image color_0205.jpg/color_0301.jpg does not exist.
E0726 22:25:12.706663 15466 pairing.cc:74] Image color_0205.jpg/color_0301.jpg does not exist.
E0726 22:25:12.706670 15466 pairing.cc:74] Image color_0205.jpg/color_0302.jpg does not exist.
E0726 22:25:12.706676 15466 pairing.cc:74] Image color_0205.jpg/color_0302.jpg does not exist.
E0726 22:25:12.706682 15466 pairing.cc:74] Image color_0205.jpg/color_0302.jpg does not exist.
E0726 22:25:12.706688 15466 pairing.cc:74] Image color_0205.jpg/color_0303.jpg does not exist.
E0726 22:25:12.706694 15466 pairing.cc:74] Image color_0205.jpg/color_0303.jpg does not exist.
E0726 22:25:12.706701 15466 pairing.cc:74] Image color_0205.jpg/color_0303.jpg does not exist.
E0726 22:25:12.706707 15466 pairing.cc:74] Image color_0205.jpg/color_0304.jpg does not exist.
E0726 22:25:12.706713 15466 pairing.cc:74] Image color_0205.jpg/color_0304.jpg does not exist.
E0726 22:25:12.706719 15466 pairing.cc:74] Image color_0205.jpg/color_0305.jpg does not exist.
E0726 22:25:12.706725 15466 pairing.cc:74] Image color_0205.jpg/color_0305.jpg does not exist.
E0726 22:25:12.706732 15466 pairing.cc:74] Image color_0205.jpg/color_0306.jpg does not exist.
E0726 22:25:12.706738 15466 pairing.cc:74] Image color_0205.jpg/color_0306.jpg does not exist.
E0726 22:25:12.706745 15466 pairing.cc:74] Image color_0205.jpg/color_0307.jpg does not exist.
E0726 22:25:12.706751 15466 pairing.cc:74] Image color_0205.jpg/color_0307.jpg does not exist.
E0726 22:25:12.706758 15466 pairing.cc:74] Image color_0205.jpg/color_0308.jpg does not exist.
E0726 22:25:12.706763 15466 pairing.cc:74] Image color_0205.jpg/color_0309.jpg does not exist.
I0726 22:25:12.706795 15466 timer.cc:91] Elapsed time: 0.002 [minutes]
generating sfm point cloud...
I0726 22:25:12.795423 15485 misc.cc:198]
==============================================================================
Partitioning scene
==============================================================================
I0726 22:25:12.796788 15485 hierarchical_mapper.cc:132] Reading images...
I0726 22:25:12.796967 15485 scene_clustering.cc:315] Reading scene graph...
I0726 22:25:12.797006 15485 scene_clustering.cc:320] Partitioning scene graph...
I0726 22:25:12.797024 15485 hierarchical_mapper.cc:148]   Cluster 1 with 0 images
I0726 22:25:12.797034 15485 hierarchical_mapper.cc:153] Clusters have 0 images
I0726 22:25:12.797044 15485 misc.cc:198]
==============================================================================
Reconstructing clusters
==============================================================================
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
*** Aborted at 1722032712 (unix time) try "date -d @1722032712" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3eb00003c7d) received by PID 15485 (TID 0x7ef46c364000) from PID 15485; stack trace: ***
    @     0x7ef471dd0046 (unknown)
    @     0x7ef46f642520 (unknown)
    @     0x7ef46f6969fc pthread_kill
    @     0x7ef46f642476 raise
    @     0x7ef46f6287f3 abort
    @     0x7ef46faa2b9e (unknown)
    @     0x7ef46faae20c (unknown)
    @     0x7ef46faae277 std::terminate()
    @     0x7ef46faae4d8 __cxa_throw
    @     0x7ef46faa54cd (unknown)
    @     0x614723f17eee colmap::ReconstructionManager::Get()
    @     0x614723e95b64 colmap::HierarchicalMapperController::Run()
    @     0x614723de5ebd colmap::RunHierarchicalMapper()
    @     0x614723dc90bb main
    @     0x7ef46f629d90 (unknown)
    @     0x7ef46f629e40 __libc_start_main
    @     0x614723dcfa05 _start
Error executing colmap hierarchical_mapper: Command '['colmap', 'hierarchical_mapper', '--database_path', '/home/dev/A/Pipelines/ontario/camera_calibration/unrectified/database.db', '--image_path', '/home/dev/A/Pipelines/ontario/inputs/images', '--output_path', '/home/dev/A/Pipelines/ontario/camera_calibration/unrectified/sparse', '--Mapper.ba_global_function_tolerance', '0.000001']' died with <Signals.SIGABRT: 6>.
(hierarchical_3d_gaussians) dev@gaussian-splatter-9000:~/A/Pipelines/hierarchical-3d-gaussians$
```



Seems to be an issue upstream in the paring process. My matches txt also appears to be valid

**Comment by PLUS-WAVE** [comment]
> Also experiencing the same issue...
> 
> When i comment out the if statement, it crashes here:
> 
> ```
> E0726 22:25:12.706657 15466 pairing.cc:74] Image color_0205.jpg/color_0301.jpg does not exist.
> E0726 22:25:12.706663 15466 pairing.cc:74] Image color_0205.jpg/color_0301.jpg does not exist.
> E0726 22:25:12.706670 15466 pairing.cc:74] Image color_0205.jpg/color_0302.jpg does not exist.
> E0726 22:25:12.706676 15466 pairing.cc:74] Image color_0205.jpg/color_0302.jpg does not exist.
> E0726 22:25:12.706682 15466 pairing.cc:74] Image color_0205.jpg/color_0302.jpg does not exist.
> E0726 22:25:12.706688 15466 pairing.cc:74] Image color_0205.jpg/color_0303.jpg does not exist.
> E0726 22:25:12.706694 15466 pairing.cc:74] Image color_0205.jpg/color_0303.jpg does not exist.
> E0726 22:25:12.706701 15466 pairing.cc:74] Image color_0205.jpg/color_0303.jpg does not exist.
> E0726 22:25:12.706707 15466 pairing.cc:74] Image color_0205.jpg/color_0304.jpg does not exist.
> E0726 22:25:12.706713 15466 pairing.cc:74] Image color_0205.jpg/color_0304.jpg does not exist.
> E0726 22:25:12.706719 15466 pairing.cc:74] Image color_0205.jpg/color_0305.jpg does not exist.
> E0726 22:25:12.706725 15466 pairing.cc:74] Image color_0205.jpg/color_0305.jpg does not exist.
> E0726 22:25:12.706732 15466 pairing.cc:74] Image color_0205.jpg/color_0306.jpg does not exist.
> E0726 22:25:12.706738 15466 pairing.cc:74] Image color_0205.jpg/color_0306.jpg does not exist.
> E0726 22:25:12.706745 15466 pairing.cc:74] Image color_0205.jpg/color_0307.jpg does not exist.
> E0726 22:25:12.706751 15466 pairing.cc:74] Image color_0205.jpg/color_0307.jpg does not exist.
> E0726 22:25:12.706758 15466 pairing.cc:74] Image color_0205.jpg/color_0308.jpg does not exist.
> E0726 22:25:12.706763 15466 pairing.cc:74] Image color_0205.jpg/color_0309.jpg does not exist.
> I0726 22:25:12.706795 15466 timer.cc:91] Elapsed time: 0.002 [minutes]
> generating sfm point cloud...
> I0726 22:25:12.795423 15485 misc.cc:198]
> ==============================================================================
> Partitioning scene
> ==============================================================================
> I0726 22:25:12.796788 15485 hierarchical_mapper.cc:132] Reading images...
> I0726 22:25:12.796967 15485 scene_clustering.cc:315] Reading scene graph...
> I0726 22:25:12.797006 15485 scene_clustering.cc:320] Partitioning scene graph...
> I0726 22:25:12.797024 15485 hierarchical_mapper.cc:148]   Cluster 1 with 0 images
> I0726 22:25:12.797034 15485 hierarchical_mapper.cc:153] Clusters have 0 images
> I0726 22:25:12.797044 15485 misc.cc:198]
> ==============================================================================
> Reconstructing clusters
> ==============================================================================
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
> *** Aborted at 1722032712 (unix time) try "date -d @1722032712" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGABRT (@0x3eb00003c7d) received by PID 15485 (TID 0x7ef46c364000) from PID 15485; stack trace: ***
>     @     0x7ef471dd0046 (unknown)
>     @     0x7ef46f642520 (unknown)
>     @     0x7ef46f6969fc pthread_kill
>     @     0x7ef46f642476 raise
>     @     0x7ef46f6287f3 abort
>     @     0x7ef46faa2b9e (unknown)
>     @     0x7ef46faae20c (unknown)
>     @     0x7ef46faae277 std::terminate()
>     @     0x7ef46faae4d8 __cxa_throw
>     @     0x7ef46faa54cd (unknown)
>     @     0x614723f17eee colmap::ReconstructionManager::Get()
>     @     0x614723e95b64 colmap::HierarchicalMapperController::Run()
>     @     0x614723de5ebd colmap::RunHierarchicalMapper()
>     @     0x614723dc90bb main
>     @     0x7ef46f629d90 (unknown)
>     @     0x7ef46f629e40 __libc_start_main
>     @     0x614723dcfa05 _start
> Error executing colmap hierarchical_mapper: Command '['colmap', 'hierarchical_mapper', '--database_path', '/home/dev/A/Pipelines/ontario/camera_calibration/unrectified/database.db', '--image_path', '/home/dev/A/Pipelines/ontario/inputs/images', '--output_path', '/home/dev/A/Pipelines/ontario/camera_calibration/unrectified/sparse', '--Mapper.ba_global_function_tolerance', '0.000001']' died with <Signals.SIGABRT: 6>.
> (hierarchical_3d_gaussians) dev@gaussian-splatter-9000:~/A/Pipelines/hierarchical-3d-gaussians$
> ```
> 
> Seems to be an issue upstream in the paring process. My matches txt also appears to be valid

same issue！😭

**Comment by ameuleman** [comment]
Hi @shankar-anantak @PLUS-WAVE,
Please put your images into a subfolder in `images/` e. g. `images/cam1/`

**Comment by PLUS-WAVE** [comment]
> Hi @shankar-anantak @PLUS-WAVE,嗨@shankar-anantak @PLUS-WAVE， Please put your images into a subfolder in `images/` e. g. `images/cam1/`请将您的图像放入 `images/` e 中的子文件夹中。 G。 `images/cam1/`

this is my working folder:

```
.
├── camera_calibration
│   ├── aligned
│   │   └── sparse
│   │       └── 0
│   ├── rectified
│   └── unrectified
│       ├── database.db
│       ├── database.db-shm
│       ├── database.db-wal
│       ├── matching.txt
│       └── sparse
└── inputs
    └── images
        └── cam1
            ├── 000400_00.png
            ...
            └── 000480_00.png
```

**Comment by PLUS-WAVE** [comment]
Now my monocular dataset works fine. I added camera intrinsics and extrinsics to do SfM. Monocular SfM for pure forward motion often fails without extrinsics. 
And to avoid the initial problem, I replaced custom_matcher with exhaustive_matcher (should have no effect)

**Comment by zhicong01** [comment]
> Now my monocular dataset works fine. I added camera intrinsics and extrinsics to do SfM. Monocular SfM for pure forward motion often fails without extrinsics. And to avoid the initial problem, I replaced custom_matcher with exhaustive_matcher (should make no difference)

Hello,  
May I ask how to modify the code to perform a replacement?  
Thank you!

**Comment by PLUS-WAVE** [comment]
> > Now my monocular dataset works fine. I added camera intrinsics and extrinsics to do SfM. Monocular SfM for pure forward motion often fails without extrinsics. And to avoid the initial problem, I replaced custom_matcher with exhaustive_matcher (should make no difference)
> 
> Hello, 你好， May I ask how to modify the code to perform a replacement?请问如何修改代码进行替换？ Thank you! 谢谢你！


You can refer to this function to modify **`generate_colmap.py`**:  
[https://github.com/zju3dv/street_gaussians/blob/5cf9ca5ba22878af15cb738fae07054a36d7b21f/script/waymo/colmap_waymo_full.py#L26](https://github.com/zju3dv/street_gaussians/blob/5cf9ca5ba22878af15cb738fae07054a36d7b21f/script/waymo/colmap_waymo_full.py#L26)  

The key is to use `point_triangulator`'s `--input_path {model_dir}` to input extrinsics and intrinsics instead of `hierarchical_mapper`. And, replace `custom_matcher` with `exhaustive_matcher` is simple: Replace the relevant part of [custom_matcher](https://github.com/graphdeco-inria/hierarchical-3d-gaussians/blob/85777b143010dedb7bc370a4591de3498fe878bb/preprocess/generate_colmap.py#L92C1-L115C20) with the following:  

```python
## Feature matching
print("Matching features...")
colmap_matches_importer_args = [
    colmap_exe, "exhaustive_matcher",
    "--database_path", f"{args.project_dir}/camera_calibration/unrectified/database.db"
]
try:
    subprocess.run(colmap_matches_importer_args, check=True)
except subprocess.CalledProcessError as e:
    print(f"Error executing colmap matches_importer: {e}")
    sys.exit(1)
```
