### ISSUE TITLE
Please help me, I have a permissions issue

### ISSUE THREAD

**Issue by WangYu0611** [graphdeco-inria/hierarchical-3d-gaussians#33]
(hierarchical_3d_gaussians) wy@wy-System-Product-Name:~/hierarchical-3d-gaussians$ python preprocess/generate_depth.py --project_dir example
generating depth maps using Depth-Anything-V2.
Estimating depth for example/camera_calibration/rectified/images/cam6
Traceback (most recent call last):
  File "/home/wy/hierarchical-3d-gaussians/preprocess/generate_depth.py", line 49, in <module>
    os.makedirs(full_depth_path, exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '../../example'

**Comment by hecodeit** [comment]
@WangYu0611 Same issue, how to solve the problem?

**Comment by WangYu0611** [comment]
> @WangYu0611 Same issue, how to solve the problem?

I set up my file structure according to the directory given by the project, copied and pasted it, and there was no problem.
