### ISSUE TITLE
SIBR_Viewer, WSL, 22.04 - it doesn't start

### ISSUE THREAD

**Issue by kuki83** [graphdeco-inria/hierarchical-3d-gaussians#42]
Is there anyone here who can help me run SIBR?

(hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:/ hierarchical-3d-gaussians$ SIBR_viewers/install/bin/SIBR_gaussianHierarchyViewer_app --path ${DATASET_DIR}/camera_calibration/aligned --scaffold ${DATASET_DIR}/output/scaffold/point_cloud/iteration_30000 --model-path ${DATASET_DIR}/output/merged.hier --images-path ${DATASET_DIR}/camera_calibration/rectified/images
[SIBR] --  INFOS  --:   Initialization of GLFW
WARNING: dzn is not a conformant Vulkan implementation, testing use only.
WARNING: dzn is not a conformant Vulkan implementation, testing use only.
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Microsoft Direct3D12 (NVIDIA GeForce RTX 4090)) doesn't support base Zink requirements: feats.features.logicOp have_EXT_custom_border_color have_EXT_line_rasterization
[SIBR] --  INFOS  --:   OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3 git2407250600.76ae27~oibaf~j (git-76ae27e 2024-07-25 jammy-oi[major: 4, minor: 6]
Number of input Images to read: 5822
Number of Cameras set up: 5822
LOADSFM: Try to open data/small_city/camera_calibration/aligned/sparse/0/points3D.bin
Num 3D pts 2390040
[SIBR] --  INFOS  --:   SfM Mesh 'data/small_city/camera_calibration/aligned/sparse/0/points3d.bin successfully loaded.  (2390040) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
 USED RES (1024,690) scene w h 1024 : 690 NAME pass1_0000.jpg
Warning: GLParameter user_color does not exist in shader PointBased
[SIBR] --  INFOS  --:   Allowing up to 18598279 Gaussians in VRAM
Using 12713828167 bytes for scene
[SIBR] --  INFOS  --:   Initializing Raycaster
Cameras ID inconsistent. Setting default interpolation path.
[SIBR] --  INFOS  --:   Interactive camera using (0.009,1100) near/far planes.
Warning: GLParameter user_color does not exist in shader points_shader
Switched to trackball mode.
images_path: data/small_city/camera_calibration/rectified/images
Cameras ID inconsistent. Setting default interpolation path.
Segmentation fault
(hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$

**Comment by Snosixtyboo** [comment]
Can you successfully run other opengl applications through your WSL? Like glxgears, e.g.?

**Comment by 000skysky000** [comment]
@Snosixtyboo
Thanks for the responses. Excellent work!
I have a similar problem, but glxgears run perfect in docker .

`root@leador-System-Product-Name:/media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/hierarchical-3d-gaussians# SIBR_viewers/install/bin/SIBR_gaussianHierarchyViewer_app --path ${DATASET_DIR}/camera_calibration/aligned --scaffold ${DATASET_DIR}/output/scaffold/point_cloud/iteration_30000 --model-path ${DATASET_DIR}/output/merged.hier --images-path ${DATASET_DIR}/camera_calibration/rectified/images --budget 6000
[SIBR] --  INFOS  --:	Initialization of GLFW
[SIBR] --  INFOS  --:	OpenGL Version: 4.5 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1[major: 4, minor: 5]
Number of input Images to read: 5822
Number of Cameras set up: 5822
[SIBR] --  INFOS  --:	Error: can't load mesh '/media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/small_city/camera_calibration/aligned/sparse/0/points3d.txt.
[SIBR] --  INFOS  --:	Error: can't load mesh '/media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/small_city/camera_calibration/aligned/sparse/0/points3d.ply.
[SIBR] --  INFOS  --:	Error: can't load mesh '/media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/small_city/camera_calibration/aligned/sparse/0/points3d.obj.
LOADSFM: Try to open /media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/small_city/camera_calibration/aligned/sparse/0/points3D.bin
Num 3D pts 2390040
[SIBR] --  INFOS  --:	SfM Mesh '/media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/small_city/camera_calibration/aligned/sparse/0/points3d.txt successfully loaded.  (2390040) vertices detected. Init GL ...
[SIBR] --  INFOS  --:	Init GL mesh complete 
 USED RES (1024,690) scene w h 1024 : 690 NAME pass1_0000.jpg
Warning: GLParameter user_color does not exist in shader PointBased
[SIBR] --  INFOS  --:	Allowing up to 8739500 Gaussians in VRAM
Using 5999999668 bytes for scene
[SIBR] --  INFOS  --:	Initializing Raycaster
Cameras ID inconsistent. Setting default interpolation path.
[SIBR] --  INFOS  --:	Interactive camera using (0.009,1100) near/far planes.
Warning: GLParameter user_color does not exist in shader points_shader
Switched to trackball mode.
images_path: /media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/small_city/camera_calibration/rectified/images
Cameras ID inconsistent. Setting default interpolation path.
Segmentation fault (core dumped)
root@leador-System-Product-Name:/media/leador/b0d7adc8-81d9-4535-9098-fadc2eb575ea3/sky/hierarchical-3d-gaussians# glxgears
3586 frames in 5.0 seconds = 716.580 FPS
`

**Comment by 000skysky000** [comment]
@kuki83 I update NViDIA driver to latest 550 version manage run

**Comment by kuki83** [comment]
> Can you successfully run other opengl applications through your WSL? Like glxgears, e.g.?


glxgears turning on.


(base) kukla@DESKTOP-6AMN05S:~$ glxgears
WARNING: dzn is not a conformant Vulkan implementation, testing use only.
WARNING: dzn is not a conformant Vulkan implementation, testing use only.
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Microsoft Direct3D12 (NVIDIA GeForce RTX 4090)) doesn't support base Zink requirements: feats.features.logicOp have_EXT_custom_border_color have_EXT_line_rasterization
1046 frames in 5.0 seconds = 209.146 FPS
954 frames in 5.0 seconds = 190.541 FPS

**Comment by kuki83** [comment]
help me. I have a problem all the time


(hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ SIBR_viewers/install/bin/SIBR_gaussianHierarchyViewer_app --path ${DATASET_DIR}/camera_calibration/aligned --scaffold ${DATASET_DIR}/output/scaffold/point_cloud/iteration_30000 --model-path ${DATASET_DIR}/output/merged.hier --images-path ${DATASET_DIR}/camera_calibration/rectified/images
[SIBR] --  INFOS  --:   Initialization of GLFW
WARNING: dzn is not a conformant Vulkan implementation, testing use only.
WARNING: dzn is not a conformant Vulkan implementation, testing use only.
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Microsoft Direct3D12 (NVIDIA GeForce RTX 4090)) doesn't support base Zink requirements: feats.features.logicOp have_EXT_custom_border_color have_EXT_line_rasterization
[SIBR] --  INFOS  --:   OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3~git2407250600.76ae27~oibaf~j (git-76ae27e 2024-07-25 jammy-oi[major: 4, minor: 6]
Number of input Images to read: 1344
Number of Cameras set up: 1344
[SIBR] --  INFOS  --:   Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.txt.
[SIBR] --  INFOS  --:   Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.ply.
[SIBR] --  INFOS  --:   Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.obj.
LOADSFM: Try to open data/city/camera_calibration/aligned/sparse/0/points3D.bin
Num 3D pts 256359
[SIBR] --  INFOS  --:   SfM Mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.txt successfully loaded.  (256359) vertices detected. Init GL ...
[SIBR] --  INFOS  --:   Init GL mesh complete
 USED RES (1027,691) scene w h 1027 : 691 NAME cam4/pass1_0835.jpg
Warning: GLParameter user_color does not exist in shader PointBased
[SIBR] --  INFOS  --:   Allowing up to 5591660 Gaussians in VRAM
Using 3856320628 bytes for scene
[SIBR] --  INFOS  --:   Initializing Raycaster
Cameras ID inconsistent. Setting default interpolation path.
[SIBR] --  INFOS  --:   Interactive camera using (0.009,1100) near/far planes.
Warning: GLParameter user_color does not exist in shader points_shader
Switched to trackball mode.
images_path: data/city/camera_calibration/rectified/images
Cameras ID inconsistent. Setting default interpolation path.
Segmentation fault
(hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ nvidia-smi
Wed Aug 21 15:28:42 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.28.03              Driver Version: 555.85         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        On  |   00000000:01:00.0  On |                  Off |
|  0%   28C    P8             10W /  450W |    1164MiB /  24564MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        On  |   00000000:02:00.0 Off |                  Off |
|  0%   27C    P8              9W /  450W |     210MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       698      G   /Xwayland                                   N/A      |
|    1   N/A  N/A       698      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+
(hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$

**Comment by lzxzy** [comment]
Is there any solution for this issue? I also encounter the problem.

**Comment by lzxzy** [comment]
> Is there any solution for this issue? I also encounter the problem.



> help me. I have a problem all the time
> 
> (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ SIBR_viewers/install/bin/SIBR_gaussianHierarchyViewer_app --path ${DATASET_DIR}/camera_calibration/aligned --scaffold ${DATASET_DIR}/output/scaffold/point_cloud/iteration_30000 --model-path ${DATASET_DIR}/output/merged.hier --images-path ${DATASET_DIR}/camera_calibration/rectified/images [SIBR] -- INFOS --: Initialization of GLFW WARNING: dzn is not a conformant Vulkan implementation, testing use only. WARNING: dzn is not a conformant Vulkan implementation, testing use only. WARNING: Some incorrect rendering might occur because the selected Vulkan device (Microsoft Direct3D12 (NVIDIA GeForce RTX 4090)) doesn't support base Zink requirements: feats.features.logicOp have_EXT_custom_border_color have_EXT_line_rasterization [SIBR] -- INFOS --: OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3~git2407250600.76ae27~oibaf~j (git-76ae27e 2024-07-25 jammy-oi[major: 4, minor: 6] Number of input Images to read: 1344 Number of Cameras set up: 1344 [SIBR] -- INFOS --: Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.txt. [SIBR] -- INFOS --: Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.ply. [SIBR] -- INFOS --: Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.obj. LOADSFM: Try to open data/city/camera_calibration/aligned/sparse/0/points3D.bin Num 3D pts 256359 [SIBR] -- INFOS --: SfM Mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.txt successfully loaded. (256359) vertices detected. Init GL ... [SIBR] -- INFOS --: Init GL mesh complete USED RES (1027,691) scene w h 1027 : 691 NAME cam4/pass1_0835.jpg Warning: GLParameter user_color does not exist in shader PointBased [SIBR] -- INFOS --: Allowing up to 5591660 Gaussians in VRAM Using 3856320628 bytes for scene [SIBR] -- INFOS --: Initializing Raycaster Cameras ID inconsistent. Setting default interpolation path. [SIBR] -- INFOS --: Interactive camera using (0.009,1100) near/far planes. Warning: GLParameter user_color does not exist in shader points_shader Switched to trackball mode. images_path: data/city/camera_calibration/rectified/images Cameras ID inconsistent. Setting default interpolation path. Segmentation fault (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ nvidia-smi Wed Aug 21 15:28:42 2024 +-----------------------------------------------------------------------------------------+ | NVIDIA-SMI 560.28.03 Driver Version: 555.85 CUDA Version: 12.5 | |-----------------------------------------+------------------------+----------------------+ | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |=========================================+========================+======================| | 0 NVIDIA GeForce RTX 4090 On | 00000000:01:00.0 On | Off | | 0% 28C P8 10W / 450W | 1164MiB / 24564MiB | 1% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 1 NVIDIA GeForce RTX 4090 On | 00000000:02:00.0 Off | Off | | 0% 27C P8 9W / 450W | 210MiB / 24564MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+
> 
> +-----------------------------------------------------------------------------------------+ | Processes: | | GPU GI CI PID Type Process name GPU Memory | | ID ID Usage | |=========================================================================================| | 0 N/A N/A 698 G /Xwayland N/A | | 1 N/A N/A 698 G /Xwayland N/A | +-----------------------------------------------------------------------------------------+ (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0

Is there any solution for this issue? I also encounter the problem.

**Comment by kunalkathare** [comment]
> help me. I have a problem all the time
> 
> (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ SIBR_viewers/install/bin/SIBR_gaussianHierarchyViewer_app --path ${DATASET_DIR}/camera_calibration/aligned --scaffold ${DATASET_DIR}/output/scaffold/point_cloud/iteration_30000 --model-path ${DATASET_DIR}/output/merged.hier --images-path ${DATASET_DIR}/camera_calibration/rectified/images [SIBR] -- INFOS --: Initialization of GLFW WARNING: dzn is not a conformant Vulkan implementation, testing use only. WARNING: dzn is not a conformant Vulkan implementation, testing use only. WARNING: Some incorrect rendering might occur because the selected Vulkan device (Microsoft Direct3D12 (NVIDIA GeForce RTX 4090)) doesn't support base Zink requirements: feats.features.logicOp have_EXT_custom_border_color have_EXT_line_rasterization [SIBR] -- INFOS --: OpenGL Version: 4.6 (Compatibility Profile) Mesa 24.3~git2407250600.76ae27~oibaf~j (git-76ae27e 2024-07-25 jammy-oi[major: 4, minor: 6] Number of input Images to read: 1344 Number of Cameras set up: 1344 [SIBR] -- INFOS --: Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.txt. [SIBR] -- INFOS --: Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.ply. [SIBR] -- INFOS --: Error: can't load mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.obj. LOADSFM: Try to open data/city/camera_calibration/aligned/sparse/0/points3D.bin Num 3D pts 256359 [SIBR] -- INFOS --: SfM Mesh 'data/city/camera_calibration/aligned/sparse/0/points3d.txt successfully loaded. (256359) vertices detected. Init GL ... [SIBR] -- INFOS --: Init GL mesh complete USED RES (1027,691) scene w h 1027 : 691 NAME cam4/pass1_0835.jpg Warning: GLParameter user_color does not exist in shader PointBased [SIBR] -- INFOS --: Allowing up to 5591660 Gaussians in VRAM Using 3856320628 bytes for scene [SIBR] -- INFOS --: Initializing Raycaster Cameras ID inconsistent. Setting default interpolation path. [SIBR] -- INFOS --: Interactive camera using (0.009,1100) near/far planes. Warning: GLParameter user_color does not exist in shader points_shader Switched to trackball mode. images_path: data/city/camera_calibration/rectified/images Cameras ID inconsistent. Setting default interpolation path. Segmentation fault (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ nvidia-smi Wed Aug 21 15:28:42 2024 +-----------------------------------------------------------------------------------------+ | NVIDIA-SMI 560.28.03 Driver Version: 555.85 CUDA Version: 12.5 | |-----------------------------------------+------------------------+----------------------+ | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |=========================================+========================+======================| | 0 NVIDIA GeForce RTX 4090 On | 00000000:01:00.0 On | Off | | 0% 28C P8 10W / 450W | 1164MiB / 24564MiB | 1% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+ | 1 NVIDIA GeForce RTX 4090 On | 00000000:02:00.0 Off | Off | | 0% 27C P8 9W / 450W | 210MiB / 24564MiB | 0% Default | | | | N/A | +-----------------------------------------+------------------------+----------------------+
> 
> +-----------------------------------------------------------------------------------------+ | Processes: | | GPU GI CI PID Type Process name GPU Memory | | ID ID Usage | |=========================================================================================| | 0 N/A N/A 698 G /Xwayland N/A | | 1 N/A N/A 698 G /Xwayland N/A | +-----------------------------------------------------------------------------------------+ (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ (hierarchical_3d_gaussians) kukla@DESKTOP-6AMN05S:~/hierarchical-3d-gaussians$ nvcc --version nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2022 NVIDIA Corporation Built on Wed_Sep_21_10:33:58_PDT_2022 Cuda compilation tools, release 11.8, V11.8.89 Build cuda_11.8.r11.8/compiler.31833905_0


- Even I am facing the same issue, is there any solution to this?

**Comment by enfild** [comment]
+1 to the topic.
BT from gdb:
```
(gdb) bt
#0  0x00007126ff2f3020 in  () at /lib/x86_64-linux-gnu/libcuda.so.1
#1  0x000071277d01ddc5 in  () at /usr/local/cuda-12.5/lib64/libcudart.so.12
#2  0x000071277d061bbe in cudaGraphicsMapResources () at /usr/local/cuda-12.5/lib64/libcudart.so.12
#3  0x00007127808f8b4f in sibr::HierarchyView::onRenderIBR(sibr::IRenderTarget&, sibr::Camera const&) (this=0x5ed49029bb50, dst=warning: RTTI symbol not found for class 'sibr::RenderTarget<unsigned char, 3u>'
..., eye=...)
    at /hierarchical-3d-gaussians/SIBR_viewers/src/projects/hierarchyviewer/renderer/HierarchyView.cpp:928
#4  0x00007127803cbe51 in sibr::MonoRdrMode::render(sibr::ViewBase&, sibr::Camera const&, sibr::Viewport const&, sibr::IRenderTarget*)
    (this=0x5ed4966e4640, view=..., eye=..., viewport=..., optDest=0x5ed4966e1ba0) at /hierarchical-3d-gaussians/SIBR_viewers/src/core/view/RenderingMode.cpp:72
#5  0x0000712780359300 in sibr::MultiViewBase::IBRSubView::render(std::shared_ptr<sibr::IRenderingMode> const&, sibr::Viewport const&) const
    (this=0x5ed490302560, rm=std::shared_ptr<sibr::IRenderingMode> (use count 1, weak count 0) = {...}, renderViewport=...)
    at /hierarchical-3d-gaussians/SIBR_viewers/src/core/view/MultiViewManager.cpp:433
#6  0x000071278035743d in sibr::MultiViewBase::renderSubView(sibr::MultiViewBase::SubView&) (this=0x7ffd6dfc5c40, subview=...)
    at /hierarchical-3d-gaussians/SIBR_viewers/src/core/view/MultiViewManager.cpp:220
#7  0x0000712780355d4c in sibr::MultiViewBase::onRender(sibr::Window&) (this=0x7ffd6dfc5c40, win=...)
    at /hierarchical-3d-gaussians/SIBR_viewers/src/core/view/MultiViewManager.cpp:91
#8  0x000071278035970d in sibr::MultiViewManager::onRender(sibr::Window&) (this=0x7ffd6dfc5c40, win=...)
    at /hierarchical-3d-gaussians/SIBR_viewers/src/core/view/MultiViewManager.cpp:478
#9  0x00005ed48f998570 in main(int, char**) (ac=13, av=0x7ffd6dfc6148)
    at /hierarchical-3d-gaussians/SIBR_viewers/src/projects/hierarchyviewer/apps/gaussianHierarchyViewer/main.cpp:139
```

The pipeline was started via Docker with X11

**Comment by 000skysky000** [comment]
@enfild Have u figure it out yet ? I get exact same problem it bother me for weeks, Can u help me please.

**Comment by enfild** [comment]
@000skysky000 if you use docker, that may help you:
```
--privileged --device /dev/nvidia-modeset --device /dev/dri/card0 --gpus all -e DISPLAY -e NVIDIA_DRIVER_CAPABILITIES=all -e __GLX_VENDOR_LIBRARY_NAME=nvidia
```

**Comment by 000skysky000** [comment]
> [@000skysky000](https://github.com/000skysky000) if you use docker, that may help you:
> 
> ```
> --privileged --device /dev/nvidia-modeset --device /dev/dri/card0 --gpus all -e DISPLAY -e NVIDIA_DRIVER_CAPABILITIES=all -e __GLX_VENDOR_LIBRARY_NAME=nvidia
> ```

oh my GOD ! it work ! big thanks~
