### ISSUE TITLE
from gaussian_hierarchy._C import expand_to_size, get_interpolation_weights

### ISSUE THREAD

**Issue by rayflower2020** [graphdeco-inria/hierarchical-3d-gaussians#59]
Cannot find reference '_C' in 'imported module gaussian_hierarchy'

**Comment by ameuleman** [comment]
Hi, 
did `pip install -r requirements.txt` run smoothly?

**Comment by drewtu2** [comment]
I think I have a related issue. 
```
Traceback (most recent call last):                                                                                                                                                                                    │
  File "/home/atu/projects/3dgs/hierarchical-3d-gaussians/train_coarse.py", line 15, in <module>                                                                                                                      │
    from gaussian_renderer import render_coarse, network_gui                                                                                                                                                          │
  File "/home/atu/projects/3dgs/hierarchical-3d-gaussians/gaussian_renderer/__init__.py", line 14, in <module>                                                                                                        │
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer                                                                                                                         │
  File "/home/atu/miniconda3/envs/hierarchical_3d_gaussians/lib/python3.12/site-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>                                                               │
    from . import _C                                                                                                                                                                                                  │
ImportError: /home/atu/miniconda3/envs/hierarchical_3d_gaussians/lib/python3.12/site-packages/diff_gaussian_rasterization/_C.cpython-312-x86_64-linux-gnu.so: undefined symbol: __cxa_call_terminate                  │
```

As far as I can tell, `pip install -r` worked fine. 

I've completely flushed and rebuilt the Conda environment  a few times and I still can't seem to get around this error. 

This is the closest [SO](https://stackoverflow.com/questions/67117097/c-cpython-38-x86-64-linux-gnu-so-undefined-symbol-zn6caffe28typemeta21-typem) post I could find which seems to suggest there might be a mismatch in versions somewhere. 

I'm running with CUDA 11.8, Ubuntu 20.04, GCC 9.4.0. I know the README was tested on 22.04, and not 20.04 and a higher GCC version... Not sure if this is the cause...
